# Generated by Django 4.2 on 2024-04-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramlist',
            name='logic_condition_id',
            field=models.ForeignKey(db_column='logic_condition_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='logic_builder.logiccondition'),
        ),
        migrations.AlterField(
            model_name='paramlist',
            name='logic_id',
            field=models.ForeignKey(db_column='logic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='logic_builder.logicbuilder'),
        ),
        migrations.AlterField(
            model_name='paramlist',
            name='param_type_id',
            field=models.ForeignKey(db_column='param_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='logic_builder.paramtype'),
        ),
    ]
